# Generated by Django 2.0.8 on 2018-09-26 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_user_is_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_artist',
            new_name='is_seller',
        ),
    ]
